AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 50
Layout/LineLength:
  Max: 200
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumberedParameters:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
